steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--platform",
        "linux/amd64",
        "-t",
        "gcr.io/$PROJECT_ID/ml-docker-image",
        ".",
      ]
images:
  - "gcr.io/$PROJECT_ID/mi-imagen"
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
