name: Deploy FastAPI to Cloud Run on Push to Main

on:
  push:
    branches: [master-draft] # Cambia a "master" si es tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Ajusta a tu versión de Python
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and tag Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: fastapi-app # Nombre de tu servicio en Cloud Run
          region: us-central1 # Ajusta a tu región
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:latest
